spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql2
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
      host: localhost
      port: 1025
      username: sid
      password: sid
      properties:
        mail:
          smtp:
            trust: "*"
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000